config/routes.rb
Moment::Application.routes.draw do
  root :to => 'pages#index'

  get '/gallery', :to => 'pages#gallery'
  get '/library/(:album_id)', :to => 'library#albums', :as => 'library'
  get '/new_album', :to => 'library#new_album', :as => 'new_album'
  get '/upload', :to => 'library#upload'
  get '/profile', :to => 'profile#show'
  get '/profile/edit', :to => 'profile#edit'
  put '/profile/update', :to => 'profile#update'

  resources :albums, :only => [:create, :update, :destroy]
  

end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :title, :description

  belongs_to :user
  has_many :photos, :dependent => :destroy

  validates :title, :presence => true, :length => { :maximum => 140 }
  validates :user_id, :presence => true
  validates :description, :length => { :maximum => 500 }

  default_scope :order => 'albums.title ASC'
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :description

  belongs_to :album

  has_attached_file :image,
    :styles => { :thumb => ["200x150#", :jpg], :formal => ["800x600^", :jpg] }

  default_scope :order => 'photos.created_at ASC'
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User

  attr_accessible :avatar, :name

  has_many :albums, :dependent => :destroy

  validates :name, 
    :length =>  { :maximum => 50 }

  has_attached_file :avatar,
    :styles => { :profile => ["200x180#", :jpg], :thumb => ["40x40#", :jpg] }

  def alias
    return self.email.split('@').first if self.name.blank?
    self.name
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_filter :authorize

  def create
    @album = current_user.albums.build(params[:album])
    if @album.save
      redirect_to library_path
    else
      render 'library/new_album'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end
end

app/controllers/library_controller.rb
class LibraryController < ApplicationController
  before_filter :authorize

  def albums
    @title = 'Library - Albums'
    if not params.has_key?(:album_id)
      @album = current_user.albums.first
    else
      @album = current_user.albums.where(id: params[:album_id]).first || not_found
    end
  end

  def new_album
    @title = 'Library - New album'
    @album = current_user.albums.build
  end

  def upload
    @title = 'Library - Upload'
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  before_filter :authorize, :except => ['index']

  def index
    if signed_in?
      redirect_to library_path
    else
      @ignore_container = true
      render :template => 'pages/home'
    end
  end
  
  def gallery
    @title = 'Gallery'
  end
end

app/controllers/photos_controller.rb
class AlbumsController < ApplicationController
  before_filter :authorize

end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_filter :authorize

  def show
    @title = 'Profile'
  end

  def edit
    @title = "Edit profile"
  end

  def update
    if current_user.update_attributes(params[:user])
      redirect_to profile_path
    else
      render 'profile/edit'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_container.html.haml
.row
  .columns.small-12
    .container
      - flash.each do |key, value|
        .div.alert-box{data: {alert: ''}, class: "#{key}"}
          = value
          %a{href: "#", class: "close"} &times;
      = content

app/views/layouts/_footer.html.haml
%footer &copy; 2008 - 2013 Rui

app/views/layouts/_header.html.haml
%nav.top-bar
  %ul.title-area
    %li.name
      %h1
        %a{href: root_path}
          = Moment
    %li.toggle-topbar.menu-icon
      %a{href: "#"}
        %span

  %section.top-bar-section
    - if signed_in?
      %ul.left
        %li
          = link_to "Gallery", gallery_path
        %li
          = link_to "Library", library_path
        %li
          = link_to "Profile", profile_path
    %ul.right
      - if signed_in?
        %li= link_to 'Sign out', sign_out_path, method: :delete
      - else
        %li= link_to 'Log in', sign_in_path
      

app/views/layouts/application.html.haml
%html
  %head
    %title= @title.blank? ? "Moment" : "#{@title} | Moment"
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    - if !@ignore_container
      = render "layouts/container", :content => yield
    - else
      = yield
    = debug(params) if Rails.env.development?
    = render 'layouts/footer'

app/views/library/_album_fields.html.haml
.row
  .columns.small-12
    = form.label :title
    = form.text_field :title, :placeholder => "Give album a title"
.row
  .columns.small-12
    = form.label :description
    = form.text_area :description, :placeholder => "Describes the album here...", :class => "medium"

app/views/library/_nav.html.haml
%ul.side-nav
  %li.title Library
  %li.sub-item{:class => "#{'active' if !@album.nil? and @album.new_record?}"}
    = link_to "Create new album", new_album_path
  %li.divider
  %li.title Albums
  - current_user.albums.select { |x| not x.new_record? }.each do |album|
    %li.sub-item{:class => "#{'active' if !@album.nil? and @album == album}"}
      = link_to album.title, library_path(:album_id => album.id)

app/views/library/albums.html.haml
%h2 Library
.row
  .columns.large-3.small-12
    = render 'library/nav'
  .columns.large-9.small-12
    - if @album.nil?
      = render 'shared/alert_box', :type => :secondary, :message => 'No album is found.'
    - else
      %ul.small-block-grid-2.large-block-grid-3
        - @album.photos.each do |photo|
          %li
            = link_to("#") do
              = image_tag(photo.image.url(:thumb))

app/views/library/new_album.html.haml
%h2 New album
.row
  .columns.large-3.small-12
    = render 'library/nav'
  .columns.large-9.small-12
    = render 'shared/model_errors', :m => @album
    = form_for @album, :html => {:class => "bordered"} do |form|
      = render 'library/album_fields', :form => form
      .row
        .columns.small-12
          = form.submit "Create", :class => "button"
          = link_to "Cancel", request.referrer, :class => "button secondary"

app/views/library/upload.html.haml
/= render 'library/nav', :request => :upload

app/views/pages/home.html.haml
.hero
  .row
    .columns.small-12
      %h1.masthead Moment
      %p.lead
        This site is built for my families and friends to host and share photos.
      %p
        = link_to 'Sign up for free', sign_up_path, :class => 'button large sign-up'
      %p
        = link_to 'Log in', sign_in_path, :class => 'button'

app/views/shared/_alert_box.html.haml
= content_tag('div', {class: type.to_s, data: {alert: ''}}) do
  = message

app/views/shared/_model_errors.html.haml
- if m.errors.any?
  .alert-box.alert{data: {alert: ''}}
    %strong Oops, there were some problems...
    %ul
      - m.errors.full_messages.each do |msg|
        %li= "#{msg}"

app/views/users/_form.html.haml
.row
  .columns.small-12
    = form.label :email
    = form.text_field :email, :type => "email"
.row
  .columns.small-12
    = form.label :password
    = form.password_field :password

app/views/users/new.html.haml
.row
  .columns.small-12.large-6.large-centered
    = render 'shared/model_errors', :m => @user
    = form_for @user, :html => {:class => "bordered margin-top"} do |form|
      %h4 Sign up
      = render 'users/form', :form => form
      .row
        .columns.small-12
          = form.submit :class => "button"
          = link_to "Cancel", root_path